In [ ]:
from pathlib import Path
import sys
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import optuna
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer



from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

sys.path.append(str(Path().resolve().parent))
import src.data_processing.data_processing as dp
import src.data_processing.building_dataset as bd

/mnt/d/ml_project/ml_project_2026/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = dp.load_data('../data/raw/grades.csv')

/mnt/d/ml_project/ml_project_2026/src/data_processing/data_processing.py:23: DtypeWarning: Columns (0: course, 1: module, 2: academic_year) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, sep = ';')

In [4]:
df = dp.clean_data(df)
df = dp.process_data(df)

df_final = bd.make_features_for_status(df)
df_final.head()

,student_id_hash,avg_grade,count_grades,proportion_retake,proportion_retake_com,student_status,course_1,course_2,course_3,course_4,...,place_type_Внеконкурсное поступление,place_type_Коммерческие,place_type_Коммерческие за счет средств вуза,place_type_Коммерческие за счет средств вуза для иностранных граждан,place_type_Коммерческие места для иностранных граждан,place_type_Места с оплатой стоимости обучения на договорной основе,"place_type_Места, обеспеченные государственным финансированием",place_type_По межправительственным соглашениям,place_type_Сетевой студент,place_type_Целевые
0,00000d86dad0d3c197341f776bb61a1d,8.166667,24,0.000000,0.000000,graduated,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0001dd443aff5c0800694730323c3d7d,6.973913,115,0.034783,0.008696,study,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,00035b28bedc6d3a0336cb61a841d79b,7.214286,14,0.000000,0.000000,study,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,00044a704df898b9a87faf40795d62b6,8.454545,22,0.000000,0.000000,graduated,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0004d03d5c41e468a521ed8a964fe889,7.250000,16,0.062500,0.000000,study,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_final = dp.str_to_int_student_status(df_final)

In [7]:
X = df_final.drop(columns=['student_id_hash', 'student_status'])
y = df_final['student_status']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train_mini = np.concat((X_train[y_train==0][:20*y_train.sum()], X_train[y_train==1]))
y_train_mini = np.concat((y_train[y_train==0][:20*y_train.sum()], y_train[y_train==1]))

In [12]:

def objective(trial, X, y):
    params = {

        'max_depth': trial.suggest_int('max_depth', 2, 30),

        'min_samples_split': trial.suggest_int(
            'min_samples_split',
            2,
            20
        ),

        'min_samples_leaf': trial.suggest_int(
            'min_samples_leaf',
            1,
            20
        ),

        'criterion': trial.suggest_categorical(
            'criterion',
            ['gini', 'entropy', 'log_loss']
        ),

        'max_features': trial.suggest_categorical(
            'max_features',
            [None, 'sqrt', 'log2']
        )
    }

    model = DecisionTreeClassifier(
        **params,
        random_state=42
    )

    score = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring='f1'
    ).mean()

    return score


def tune_decision_tree(
    X,
    y,
    n_trials: int = 50
):


    study = optuna.create_study(
        direction='maximize'
    )

    study.optimize(
        lambda trial: objective(trial, X, y),
        n_trials=n_trials
    )

    best_params = study.best_params

    print("Лучшие параметры")
    print(best_params)

    print()
    print(f"Лучший score: {study.best_value:.4f}")

    best_model = DecisionTreeClassifier(
        **best_params,
        random_state=42
    )

    best_model.fit(X, y)

    return best_model, study
best_model_DecisionTree, model_DecisionTree = tune_decision_tree(
    X_train,
    y_train,
    n_trials=100
)

[I 2026-05-18 14:23:01,126] A new study created in memory with name: no-name-b1ef27c9-7253-43f1-aed4-909dc5e26d15
[I 2026-05-18 14:23:03,419] Trial 0 finished with value: 0.6150869730860652 and parameters: {'max_depth': 23, 'min_samples_split': 7, 'min_samples_leaf': 13, 'criterion': 'log_loss', 'max_features': 'sqrt'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:04,975] Trial 1 finished with value: 0.5901855623927886 and parameters: {'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 7, 'criterion': 'gini', 'max_features': 'log2'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:06,672] Trial 2 finished with value: 0.5849741124338033 and parameters: {'max_depth': 26, 'min_samples_split': 15, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': 'log2'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:07,771] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 16, 'criterion': 'log_loss', 'max_features': 'log2'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:09,912] Trial 4 finished with value: 0.4670802115855512 and parameters: {'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 14, 'criterion': 'gini', 'max_features': 'sqrt'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:11,835] Trial 5 finished with value: 0.5900882988740987 and parameters: {'max_depth': 17, 'min_samples_split': 19, 'min_samples_leaf': 6, 'criterion': 'log_loss', 'max_features': 'log2'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:12,881] Trial 6 finished with value: 0.570200942490857 and parameters: {'max_depth': 16, 'min_samples_split': 15, 'min_samples_leaf': 16, 'criterion': 'log_loss', 'max_features': 'log2'}. Best is trial 0 with value: 0.6150869730860652.
[I 2026-05-18 14:23:14,576] Trial 7 finished with value: 0.6491382293349521 and parameters: {'max_depth': 30, 'min_samples_split': 16, 'min_samples_leaf': 5, 'criterion': 'log_loss', 'max_features': 'sqrt'}. Best is trial 7 with value: 0.6491382293349521.
[I 2026-05-18 14:23:17,187] Trial 8 finished with value: 0.813612623722506 and parameters: {'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 13, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:18,049] Trial 9 finished with value: 0.5493745859252711 and parameters: {'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 12, 'criterion': 'gini', 'max_features': 'sqrt'}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:19,268] Trial 10 finished with value: 0.7236827387122521 and parameters: {'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 19, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:20,480] Trial 11 finished with value: 0.7236827387122521 and parameters: {'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 20, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:23,409] Trial 12 finished with value: 0.7983405410380114 and parameters: {'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 19, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:27,848] Trial 13 finished with value: 0.8128694187026066 and parameters: {'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 9, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:31,888] Trial 14 finished with value: 0.8128694187026066 and parameters: {'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 9, 'criterion': 'entropy', 'max_features': None}. Best is trial 8 with value: 0.813612623722506.
[I 2026-05-18 14:23:35,189] Trial 15 finished with value: 0.8188524353376367 and parameters: {'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 15 with value: 0.8188524353376367.
[I 2026-05-18 14:23:37,677] Trial 16 finished with value: 0.8211262426145305 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:41,892] Trial 17 finished with value: 0.801532416397371 and parameters: {'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:47,428] Trial 18 finished with value: 0.7964330395300847 and parameters: {'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:49,909] Trial 19 finished with value: 0.8211262426145305 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:52,032] Trial 20 finished with value: 0.8046526452608507 and parameters: {'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'criterion': 'gini', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:55,828] Trial 21 finished with value: 0.8078068532504936 and parameters: {'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:23:59,467] Trial 22 finished with value: 0.8211262426145305 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:02,466] Trial 23 finished with value: 0.8177889862728019 and parameters: {'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:05,335] Trial 24 finished with value: 0.8116685146582597 and parameters: {'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 7, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:09,492] Trial 25 finished with value: 0.8121171614387451 and parameters: {'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 9, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:13,571] Trial 26 finished with value: 0.8079739586981075 and parameters: {'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:17,214] Trial 27 finished with value: 0.8171842090638132 and parameters: {'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 7, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:18,234] Trial 28 finished with value: 0.5870336758312801 and parameters: {'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 5, 'criterion': 'gini', 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:22,541] Trial 29 finished with value: 0.7818365966181194 and parameters: {'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:23,344] Trial 30 finished with value: 0.5326265461890306 and parameters: {'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'criterion': 'log_loss', 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:25,174] Trial 31 finished with value: 0.8023428644411498 and parameters: {'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:28,141] Trial 32 finished with value: 0.81982917715454 and parameters: {'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:32,370] Trial 33 finished with value: 0.8132714826348156 and parameters: {'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 6, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:33,244] Trial 34 finished with value: 0.0 and parameters: {'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': 'log2'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:36,199] Trial 35 finished with value: 0.8187568703495586 and parameters: {'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:36,880] Trial 36 finished with value: 0.0 and parameters: {'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 5, 'criterion': 'gini', 'max_features': 'log2'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:39,317] Trial 37 finished with value: 0.8166686089647927 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 8, 'criterion': 'log_loss', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:40,118] Trial 38 finished with value: 0.5826721010627071 and parameters: {'max_depth': 25, 'min_samples_split': 17, 'min_samples_leaf': 11, 'criterion': 'entropy', 'max_features': 'log2'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:40,932] Trial 39 finished with value: 0.477571042554141 and parameters: {'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 6, 'criterion': 'entropy', 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:45,486] Trial 40 finished with value: 0.8004414916842613 and parameters: {'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'criterion': 'log_loss', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:50,841] Trial 41 finished with value: 0.8134392929286595 and parameters: {'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:54,027] Trial 42 finished with value: 0.8184019744927717 and parameters: {'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:55,555] Trial 43 finished with value: 0.8071257044280948 and parameters: {'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:24:58,204] Trial 44 finished with value: 0.8207800683379697 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:01,186] Trial 45 finished with value: 0.8116583752441489 and parameters: {'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'criterion': 'gini', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:02,070] Trial 46 finished with value: 0.0 and parameters: {'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 15, 'criterion': 'entropy', 'max_features': 'log2'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:05,988] Trial 47 finished with value: 0.8174380232113 and parameters: {'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:06,767] Trial 48 finished with value: 0.0 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 3, 'criterion': 'log_loss', 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:09,765] Trial 49 finished with value: 0.8092474238636751 and parameters: {'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:13,246] Trial 50 finished with value: 0.8119387216064752 and parameters: {'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 6, 'criterion': 'entropy', 'max_features': None}. Best is trial 16 with value: 0.8211262426145305.
[I 2026-05-18 14:25:15,907] Trial 51 finished with value: 0.821450339816782 and parameters: {'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:19,446] Trial 52 finished with value: 0.8180774117821681 and parameters: {'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:22,558] Trial 53 finished with value: 0.8211262426145305 and parameters: {'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:25,025] Trial 54 finished with value: 0.8213013813845993 and parameters: {'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:27,015] Trial 55 finished with value: 0.8023428644411498 and parameters: {'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:28,294] Trial 56 finished with value: 0.7236827387122521 and parameters: {'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:32,181] Trial 57 finished with value: 0.8038582738170481 and parameters: {'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'criterion': 'gini', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:36,748] Trial 58 finished with value: 0.8182184559149792 and parameters: {'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:38,965] Trial 59 finished with value: 0.8171842090638132 and parameters: {'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:40,015] Trial 60 finished with value: 0.6706772603318019 and parameters: {'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': 'sqrt'}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:42,683] Trial 61 finished with value: 0.8207800683379697 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:45,157] Trial 62 finished with value: 0.8207800683379697 and parameters: {'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:50,888] Trial 63 finished with value: 0.7925111790467902 and parameters: {'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:54,806] Trial 64 finished with value: 0.8153909690687634 and parameters: {'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:56,396] Trial 65 finished with value: 0.8071257044280948 and parameters: {'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:25:58,547] Trial 66 finished with value: 0.8177889862728019 and parameters: {'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:01,895] Trial 67 finished with value: 0.8127528893788171 and parameters: {'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'criterion': 'log_loss', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:02,574] Trial 68 finished with value: 0.008510851586386647 and parameters: {'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 13, 'criterion': 'entropy', 'max_features': 'log2'}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:04,626] Trial 69 finished with value: 0.8071257044280948 and parameters: {'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:09,944] Trial 70 finished with value: 0.8038964559494325 and parameters: {'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 10, 'criterion': 'gini', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:12,605] Trial 71 finished with value: 0.8207800683379697 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:15,105] Trial 72 finished with value: 0.8078692239462357 and parameters: {'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 17, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:16,957] Trial 73 finished with value: 0.8023428644411498 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:19,783] Trial 74 finished with value: 0.8208207532218701 and parameters: {'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:24,594] Trial 75 finished with value: 0.8116424347530303 and parameters: {'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:27,366] Trial 76 finished with value: 0.8168730521598204 and parameters: {'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.
[I 2026-05-18 14:26:29,183] Trial 77 finished with value: 0.8023428644411498 and parameters: {'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 3, 'criterion': 'entropy', 'max_features': None}. Best is trial 51 with value: 0.821450339816782.

Лучшие параметры
{'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'criterion': 'entropy', 'max_features': None}

Лучший score: 0.8215

In [14]:



def objective_rf(trial, X, y):


    params = {
        'n_estimators': trial.suggest_int(
            'n_estimators',
            50,
            200
        ),

        'max_depth': trial.suggest_int(
            'max_depth',
            2,
            20
        ),

        'min_samples_split': trial.suggest_int(
            'min_samples_split',
            2,
            20
        ),

        'min_samples_leaf': trial.suggest_int(
            'min_samples_leaf',
            1,
            20
        ),

        'max_features': trial.suggest_categorical(
            'max_features',
            ['sqrt', 'log2', None]
        ),

        'bootstrap': trial.suggest_categorical(
            'bootstrap',
            [True, False]
        )
    }

    model = RandomForestClassifier(
        **params,
        class_weight='balanced',
        random_state=42,
        n_jobs=1
    )

    score = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring='f1',
        n_jobs=-1
    ).mean()

    return score


def tune_random_forest(
    X,
    y,
    n_trials: int = 50
):

    study = optuna.create_study(
        direction='maximize'
    )

    study.optimize(
        lambda trial: objective_rf(trial, X, y),
        n_trials=n_trials
    )

    best_params = study.best_params


    best_model = RandomForestClassifier(
        **best_params,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1
    )

    best_model.fit(X, y)

    return best_model, study

best_rf, study_rf = tune_random_forest(
    X_train,
    y_train,
    n_trials=50
)

[I 2026-05-18 14:48:17,950] A new study created in memory with name: no-name-0b76c3e4-6c2d-432a-b08d-b8e6e8c855ec
[I 2026-05-18 14:48:32,303] Trial 0 finished with value: 0.6210537372628276 and parameters: {'n_estimators': 137, 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 20, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.6210537372628276.
[I 2026-05-18 14:49:05,659] Trial 1 finished with value: 0.6299478438842552 and parameters: {'n_estimators': 165, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.6299478438842552.
[I 2026-05-18 14:49:26,098] Trial 2 finished with value: 0.6224597239149399 and parameters: {'n_estimators': 156, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 1 with value: 0.6299478438842552.
[I 2026-05-18 14:50:17,944] Trial 3 finished with value: 0.6013646567137405 and parameters: {'n_estimators': 169, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 1 with value: 0.6299478438842552.
[I 2026-05-18 14:50:34,837] Trial 4 finished with value: 0.6339501255520071 and parameters: {'n_estimators': 103, 'max_depth': 14, 'min_samples_split': 19, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 4 with value: 0.6339501255520071.
[I 2026-05-18 14:59:01,916] Trial 5 finished with value: 0.4780827456094635 and parameters: {'n_estimators': 121, 'max_depth': 18, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.6339501255520071.
[I 2026-05-18 14:59:18,339] Trial 6 finished with value: 0.5007126287836163 and parameters: {'n_estimators': 50, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 4 with value: 0.6339501255520071.
[I 2026-05-18 14:59:25,301] Trial 7 finished with value: 0.6374750253724046 and parameters: {'n_estimators': 59, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 7 with value: 0.6374750253724046.
[I 2026-05-18 14:59:51,932] Trial 8 finished with value: 0.5961768506563652 and parameters: {'n_estimators': 152, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 11, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 7 with value: 0.6374750253724046.
[I 2026-05-18 15:00:23,095] Trial 9 finished with value: 0.6125970604405135 and parameters: {'n_estimators': 182, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 7 with value: 0.6374750253724046.
[I 2026-05-18 15:01:01,119] Trial 10 finished with value: 0.5309699707238712 and parameters: {'n_estimators': 54, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True}. Best is trial 7 with value: 0.6374750253724046.
[I 2026-05-18 15:01:10,488] Trial 11 finished with value: 0.6998948463972818 and parameters: {'n_estimators': 92, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 11 with value: 0.6998948463972818.
[I 2026-05-18 15:01:20,307] Trial 12 finished with value: 0.6378224416982137 and parameters: {'n_estimators': 82, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 11 with value: 0.6998948463972818.
[I 2026-05-18 15:01:30,956] Trial 13 finished with value: 0.6849928302351801 and parameters: {'n_estimators': 87, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 11 with value: 0.6998948463972818.
[I 2026-05-18 15:01:39,665] Trial 14 finished with value: 0.6682321122544651 and parameters: {'n_estimators': 90, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 11 with value: 0.6998948463972818.
[I 2026-05-18 15:01:51,519] Trial 15 finished with value: 0.7037140315926466 and parameters: {'n_estimators': 111, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 15 with value: 0.7037140315926466.
[I 2026-05-18 15:03:59,918] Trial 16 finished with value: 0.5673844738385159 and parameters: {'n_estimators': 115, 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 13, 'max_features': None, 'bootstrap': True}. Best is trial 15 with value: 0.7037140315926466.
[I 2026-05-18 15:04:13,119] Trial 17 finished with value: 0.6960583324950035 and parameters: {'n_estimators': 137, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 15 with value: 0.7037140315926466.
[I 2026-05-18 15:04:18,055] Trial 18 finished with value: 0.6271589358669051 and parameters: {'n_estimators': 73, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 15 with value: 0.7037140315926466.
[I 2026-05-18 15:07:52,778] Trial 19 finished with value: 0.6745053102932907 and parameters: {'n_estimators': 102, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 15 with value: 0.7037140315926466.
[I 2026-05-18 15:08:07,090] Trial 20 finished with value: 0.7112256187973307 and parameters: {'n_estimators': 105, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:08:21,054] Trial 21 finished with value: 0.7094714908500748 and parameters: {'n_estimators': 103, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:08:35,663] Trial 22 finished with value: 0.6489380157883575 and parameters: {'n_estimators': 111, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:08:52,804] Trial 23 finished with value: 0.6258324369440018 and parameters: {'n_estimators': 133, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:09:04,843] Trial 24 finished with value: 0.6775673633403614 and parameters: {'n_estimators': 72, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:09:19,549] Trial 25 finished with value: 0.7032377089844658 and parameters: {'n_estimators': 108, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:09:38,068] Trial 26 finished with value: 0.6407063551354852 and parameters: {'n_estimators': 123, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:09:52,970] Trial 27 finished with value: 0.6297682092211911 and parameters: {'n_estimators': 199, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:13:22,540] Trial 28 finished with value: 0.6651168862367067 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': None, 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:13:47,544] Trial 29 finished with value: 0.5281689272271402 and parameters: {'n_estimators': 128, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 19, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:14:01,252] Trial 30 finished with value: 0.64806523110531 and parameters: {'n_estimators': 146, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 20 with value: 0.7112256187973307.
[I 2026-05-18 15:14:16,213] Trial 31 finished with value: 0.7113463909659039 and parameters: {'n_estimators': 109, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:14:31,578] Trial 32 finished with value: 0.6618909743632154 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:14:43,603] Trial 33 finished with value: 0.6482733980463887 and parameters: {'n_estimators': 96, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:14:55,237] Trial 34 finished with value: 0.6694681186735633 and parameters: {'n_estimators': 77, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:15:12,325] Trial 35 finished with value: 0.6340265160993207 and parameters: {'n_estimators': 141, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:15:30,455] Trial 36 finished with value: 0.6866678190514733 and parameters: {'n_estimators': 109, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:15:47,848] Trial 37 finished with value: 0.6323611981222826 and parameters: {'n_estimators': 128, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:16:22,515] Trial 38 finished with value: 0.6213181144663481 and parameters: {'n_estimators': 104, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:16:35,018] Trial 39 finished with value: 0.6562676118551913 and parameters: {'n_estimators': 117, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:16:44,337] Trial 40 finished with value: 0.5608733884724502 and parameters: {'n_estimators': 65, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:16:58,827] Trial 41 finished with value: 0.7022023322896109 and parameters: {'n_estimators': 107, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:17:13,136] Trial 42 finished with value: 0.6728646410113186 and parameters: {'n_estimators': 95, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:17:28,279] Trial 43 finished with value: 0.7010981899954473 and parameters: {'n_estimators': 109, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:17:45,776] Trial 44 finished with value: 0.6596506681744165 and parameters: {'n_estimators': 84, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:18:02,324] Trial 45 finished with value: 0.6409411788333317 and parameters: {'n_estimators': 113, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:21:43,275] Trial 46 finished with value: 0.6985113139405182 and parameters: {'n_estimators': 98, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:22:12,063] Trial 47 finished with value: 0.6188031824644493 and parameters: {'n_estimators': 161, 'max_depth': 17, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:22:21,444] Trial 48 finished with value: 0.6746182121933586 and parameters: {'n_estimators': 122, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.
[I 2026-05-18 15:22:33,255] Trial 49 finished with value: 0.6624917600691635 and parameters: {'n_estimators': 89, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 31 with value: 0.7113463909659039.

In [15]:

def objective_gb(trial, X, y):


    params = {

        'n_estimators': trial.suggest_int(
            'n_estimators',
            50,
            200
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.001,
            0.3,
            log=True
        ),

        'max_depth': trial.suggest_int(
            'max_depth',
            2,
            10
        ),

        'min_samples_split': trial.suggest_int(
            'min_samples_split',
            2,
            20
        ),

        'min_samples_leaf': trial.suggest_int(
            'min_samples_leaf',
            1,
            20
        ),

        'subsample': trial.suggest_float(
            'subsample',
            0.5,
            1.0
        ),

        'max_features': trial.suggest_categorical(
            'max_features',
            ['sqrt', 'log2', None]
        )
    }

    model = GradientBoostingClassifier(
        **params,
        random_state=42
    )

    score = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring='f1',
        n_jobs=-1
    ).mean()

    return score


def tune_gradient_boosting(
    X,
    y,
    n_trials: int = 50
):


    study = optuna.create_study(
        direction='maximize'
    )

    study.optimize(
        lambda trial: objective_gb(trial, X, y),
        n_trials=n_trials
    )

    best_params = study.best_params


    best_model = GradientBoostingClassifier(
        **best_params,
        random_state=42
    )

    best_model.fit(X, y)

    return best_model, study
best_gb, study_gb = tune_gradient_boosting(
    X_train,
    y_train,
    n_trials=100
)

[I 2026-05-18 15:22:36,322] A new study created in memory with name: no-name-a912ab08-9a92-4479-aafe-0631529687c4
[I 2026-05-18 15:24:52,019] Trial 0 finished with value: 0.8256227461805643 and parameters: {'n_estimators': 105, 'learning_rate': 0.05114255856418449, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 4, 'subsample': 0.5278507513112994, 'max_features': None}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:25:03,122] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 163, 'learning_rate': 0.00137256518014375, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 20, 'subsample': 0.6089946709540119, 'max_features': 'log2'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:25:26,245] Trial 2 finished with value: 0.8236785849941242 and parameters: {'n_estimators': 186, 'learning_rate': 0.2362704989023102, 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 8, 'subsample': 0.8496202389693928, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:25:35,946] Trial 3 finished with value: 0.8188025796764187 and parameters: {'n_estimators': 58, 'learning_rate': 0.1853886579223819, 'max_depth': 7, 'min_samples_split': 20, 'min_samples_leaf': 13, 'subsample': 0.9117433039937632, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:25:53,100] Trial 4 finished with value: 0.05209466589748281 and parameters: {'n_estimators': 116, 'learning_rate': 0.0074752926796120694, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 5, 'subsample': 0.8808284414198209, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:32:47,711] Trial 5 finished with value: 0.7681785685416591 and parameters: {'n_estimators': 170, 'learning_rate': 0.005739524520977168, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 12, 'subsample': 0.9540422021354322, 'max_features': None}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:35:04,672] Trial 6 finished with value: 0.7920975731520329 and parameters: {'n_estimators': 172, 'learning_rate': 0.010338269052726898, 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 15, 'subsample': 0.77586011222558, 'max_features': None}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:37:40,946] Trial 7 finished with value: 0.7985703032745317 and parameters: {'n_estimators': 149, 'learning_rate': 0.008802184019462624, 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 10, 'subsample': 0.5891241729203108, 'max_features': None}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:39:12,980] Trial 8 finished with value: 0.8111827416318027 and parameters: {'n_estimators': 169, 'learning_rate': 0.041271247025789076, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 15, 'subsample': 0.7613967206987978, 'max_features': None}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:39:47,270] Trial 9 finished with value: 0.8226186030357052 and parameters: {'n_estimators': 182, 'learning_rate': 0.2063874013154011, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 17, 'subsample': 0.8657809234065827, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:39:59,791] Trial 10 finished with value: 0.7189957324154361 and parameters: {'n_estimators': 96, 'learning_rate': 0.05392045933977488, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 1, 'subsample': 0.5101399538208453, 'max_features': 'log2'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:40:07,641] Trial 11 finished with value: 0.7373896362672623 and parameters: {'n_estimators': 89, 'learning_rate': 0.07799449334941622, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 7, 'subsample': 0.6662410803019954, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8256227461805643.
[I 2026-05-18 15:46:18,900] Trial 12 finished with value: 0.8258768676651975 and parameters: {'n_estimators': 198, 'learning_rate': 0.026860405088280324, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 4, 'subsample': 0.8063929681250931, 'max_features': None}. Best is trial 12 with value: 0.8258768676651975.
[I 2026-05-18 15:49:47,134] Trial 13 finished with value: 0.8273712192617845 and parameters: {'n_estimators': 128, 'learning_rate': 0.02704601267701383, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 1, 'subsample': 0.6853129144475965, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 15:57:25,800] Trial 14 finished with value: 0.8251819003999566 and parameters: {'n_estimators': 200, 'learning_rate': 0.02549762913078811, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'subsample': 0.6937708497543924, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:01:46,201] Trial 15 finished with value: 0.0 and parameters: {'n_estimators': 141, 'learning_rate': 0.002967246058338723, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 4, 'subsample': 0.8053911207386346, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:01:56,418] Trial 16 finished with value: 0.13059860815857244 and parameters: {'n_estimators': 70, 'learning_rate': 0.020203858236988836, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1, 'subsample': 0.7077342712666438, 'max_features': 'log2'}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:05:57,293] Trial 17 finished with value: 0.8262328463931234 and parameters: {'n_estimators': 127, 'learning_rate': 0.10644448907798795, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 6, 'subsample': 0.9893908180994924, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:10:12,464] Trial 18 finished with value: 0.8238012279921045 and parameters: {'n_estimators': 137, 'learning_rate': 0.09096672724407825, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 7, 'subsample': 0.9701764884585902, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:11:56,608] Trial 19 finished with value: 0.8197722694834129 and parameters: {'n_estimators': 119, 'learning_rate': 0.13600791790894293, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 9, 'subsample': 0.626061255611988, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:12:10,149] Trial 20 finished with value: 0.8032151377028054 and parameters: {'n_estimators': 132, 'learning_rate': 0.11397116009391053, 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 6, 'subsample': 0.7099756559822513, 'max_features': 'log2'}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:16:10,287] Trial 21 finished with value: 0.8246902982964434 and parameters: {'n_estimators': 149, 'learning_rate': 0.024098314953850713, 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 3, 'subsample': 0.8154928591894242, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:18:49,295] Trial 22 finished with value: 0.8214940459687028 and parameters: {'n_estimators': 77, 'learning_rate': 0.03664276710692341, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 3, 'subsample': 0.90828904922962, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:22:27,776] Trial 23 finished with value: 0.8177775505733591 and parameters: {'n_estimators': 112, 'learning_rate': 0.016136668851260756, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 3, 'subsample': 0.9997622004124278, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:26:30,276] Trial 24 finished with value: 0.8260735274650173 and parameters: {'n_estimators': 125, 'learning_rate': 0.014829409516936952, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 5, 'subsample': 0.6499636058099495, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:30:29,338] Trial 25 finished with value: 0.0 and parameters: {'n_estimators': 127, 'learning_rate': 0.0044744795317475635, 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 6, 'subsample': 0.5600392633633364, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:33:53,843] Trial 26 finished with value: 0.8114803105621894 and parameters: {'n_estimators': 102, 'learning_rate': 0.015053510495679812, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 2, 'subsample': 0.6629782024589451, 'max_features': None}. Best is trial 13 with value: 0.8273712192617845.
[I 2026-05-18 16:38:41,571] Trial 27 finished with value: 0.8275548209604471 and parameters: {'n_estimators': 149, 'learning_rate': 0.06462756421481887, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 8, 'subsample': 0.729035981057287, 'max_features': None}. Best is trial 27 with value: 0.8275548209604471.
[I 2026-05-18 16:38:58,380] Trial 28 finished with value: 0.7661528251095862 and parameters: {'n_estimators': 154, 'learning_rate': 0.05876187663504056, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 11, 'subsample': 0.7365095434153816, 'max_features': 'log2'}. Best is trial 27 with value: 0.8275548209604471.
[I 2026-05-18 16:43:00,020] Trial 29 finished with value: 0.8241586993305529 and parameters: {'n_estimators': 141, 'learning_rate': 0.08312603986768231, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 8, 'subsample': 0.7373200582815982, 'max_features': None}. Best is trial 27 with value: 0.8275548209604471.
[I 2026-05-18 16:45:31,621] Trial 30 finished with value: 0.8206205141385368 and parameters: {'n_estimators': 155, 'learning_rate': 0.14934644336028072, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 9, 'subsample': 0.5517267656611512, 'max_features': None}. Best is trial 27 with value: 0.8275548209604471.
[I 2026-05-18 16:49:42,762] Trial 31 finished with value: 0.8297158072215959 and parameters: {'n_estimators': 124, 'learning_rate': 0.03701911776663591, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 5, 'subsample': 0.6756093718184918, 'max_features': None}. Best is trial 31 with value: 0.8297158072215959.
[I 2026-05-18 16:52:59,089] Trial 32 finished with value: 0.8329879412662194 and parameters: {'n_estimators': 108, 'learning_rate': 0.03736563332951993, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 6, 'subsample': 0.6816427025399264, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 16:56:14,381] Trial 33 finished with value: 0.8273268880288027 and parameters: {'n_estimators': 107, 'learning_rate': 0.033890886155489894, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 8, 'subsample': 0.6853611582002398, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 16:59:27,938] Trial 34 finished with value: 0.8289094425293417 and parameters: {'n_estimators': 92, 'learning_rate': 0.05833926545185255, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 5, 'subsample': 0.6274631192464575, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 16:59:43,872] Trial 35 finished with value: 0.8152751298400999 and parameters: {'n_estimators': 85, 'learning_rate': 0.058125132814034475, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 7, 'subsample': 0.6132675698160184, 'max_features': 'sqrt'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:02:56,715] Trial 36 finished with value: 0.8308811413324522 and parameters: {'n_estimators': 97, 'learning_rate': 0.045408603772588346, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 5, 'subsample': 0.5846510800465288, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:03:03,611] Trial 37 finished with value: 0.4885631893810606 and parameters: {'n_estimators': 51, 'learning_rate': 0.04297515475496189, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 5, 'subsample': 0.5825589302496849, 'max_features': 'log2'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:06:03,854] Trial 38 finished with value: 0.7543588287051568 and parameters: {'n_estimators': 95, 'learning_rate': 0.2799823457115231, 'max_depth': 9, 'min_samples_split': 14, 'min_samples_leaf': 4, 'subsample': 0.6268154615019614, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:06:16,499] Trial 39 finished with value: 0.0 and parameters: {'n_estimators': 69, 'learning_rate': 0.001419071595314278, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 5, 'subsample': 0.537729497785826, 'max_features': 'sqrt'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:09:22,626] Trial 40 finished with value: 0.823561906309289 and parameters: {'n_estimators': 105, 'learning_rate': 0.034714875718623965, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 10, 'subsample': 0.5855843095409887, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:13:19,898] Trial 41 finished with value: 0.8260875808772902 and parameters: {'n_estimators': 112, 'learning_rate': 0.06572339949093299, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 20, 'subsample': 0.6412422033343197, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:17:34,142] Trial 42 finished with value: 0.8280357077344522 and parameters: {'n_estimators': 119, 'learning_rate': 0.04584332903460817, 'max_depth': 9, 'min_samples_split': 11, 'min_samples_leaf': 9, 'subsample': 0.719329696952326, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:20:45,760] Trial 43 finished with value: 0.8265878685056507 and parameters: {'n_estimators': 85, 'learning_rate': 0.03704443279343992, 'max_depth': 9, 'min_samples_split': 11, 'min_samples_leaf': 11, 'subsample': 0.7611147327171578, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:25:07,686] Trial 44 finished with value: 0.8011942045401328 and parameters: {'n_estimators': 119, 'learning_rate': 0.01151865857587034, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 13, 'subsample': 0.669998920362227, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:27:43,778] Trial 45 finished with value: 0.8258795802263255 and parameters: {'n_estimators': 99, 'learning_rate': 0.04951047300331638, 'max_depth': 9, 'min_samples_split': 15, 'min_samples_leaf': 6, 'subsample': 0.5026578129274538, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:28:00,303] Trial 46 finished with value: 0.655277523521466 and parameters: {'n_estimators': 91, 'learning_rate': 0.019827114380269677, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 9, 'subsample': 0.6014191103588818, 'max_features': 'sqrt'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:32:16,008] Trial 47 finished with value: 0.8258099402642316 and parameters: {'n_estimators': 111, 'learning_rate': 0.0298317506519927, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4, 'subsample': 0.7850532579083678, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:34:18,622] Trial 48 finished with value: 0.8252494712606989 and parameters: {'n_estimators': 78, 'learning_rate': 0.04954850808508613, 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 7, 'subsample': 0.56994488498283, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:38:22,139] Trial 49 finished with value: 0.8150940863495286 and parameters: {'n_estimators': 117, 'learning_rate': 0.07728474570059837, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 2, 'subsample': 0.7099423667763806, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:38:34,149] Trial 50 finished with value: 0.689875208281968 and parameters: {'n_estimators': 94, 'learning_rate': 0.0463691650624445, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 17, 'subsample': 0.6404584097574694, 'max_features': 'log2'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:44:06,507] Trial 51 finished with value: 0.828936390122714 and parameters: {'n_estimators': 177, 'learning_rate': 0.06510340871423886, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 8, 'subsample': 0.7204045431185478, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:50:11,590] Trial 52 finished with value: 0.8175789835552653 and parameters: {'n_estimators': 181, 'learning_rate': 0.09822597286395944, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 6, 'subsample': 0.6788020310404242, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:54:21,673] Trial 53 finished with value: 0.8064276774557271 and parameters: {'n_estimators': 135, 'learning_rate': 0.1555218953667039, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 8, 'subsample': 0.701652671388262, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 17:59:56,338] Trial 54 finished with value: 0.8232826487362104 and parameters: {'n_estimators': 192, 'learning_rate': 0.07332468648000919, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 10, 'subsample': 0.6566442962092583, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:00:59,107] Trial 55 finished with value: 0.8066804208741708 and parameters: {'n_estimators': 122, 'learning_rate': 0.027896270637578373, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 5, 'subsample': 0.7275163072609517, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:04:25,126] Trial 56 finished with value: 0.8138672095599485 and parameters: {'n_estimators': 102, 'learning_rate': 0.11655982246322932, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 7, 'subsample': 0.6081805701948899, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:04:44,918] Trial 57 finished with value: 0.7308645645069936 and parameters: {'n_estimators': 113, 'learning_rate': 0.021936802218663756, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'subsample': 0.6296567897529298, 'max_features': 'sqrt'}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:08:41,427] Trial 58 finished with value: 0.7896259361817919 and parameters: {'n_estimators': 107, 'learning_rate': 0.1923639344723079, 'max_depth': 9, 'min_samples_split': 14, 'min_samples_leaf': 6, 'subsample': 0.7581113069413997, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:12:01,887] Trial 59 finished with value: 0.8280614748231369 and parameters: {'n_estimators': 86, 'learning_rate': 0.039093913503523085, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 9, 'subsample': 0.714038512329699, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.
[I 2026-05-18 18:14:57,159] Trial 60 finished with value: 0.710569475982723 and parameters: {'n_estimators': 69, 'learning_rate': 0.011911973985978161, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 13, 'subsample': 0.7896806135550626, 'max_features': None}. Best is trial 32 with value: 0.8329879412662194.

In [ ]:

models = {
    'Logistic Regression': LogisticRegression(max_iter=10000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(max_depth = 6, min_samples_split =  4, min_samples_leaf = 2, criterion = 'entropy', max_features = None),
    'Random Forest': RandomForestClassifier(n_estimators = 109, max_depth =  16, min_samples_split =  5, min_samples_leaf = 1, max_features = 'log2', bootstrap = True),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators = 108, learning_rate = 0.03736563332951993,  max_depth = 8, min_samples_split = 13, min_samples_leaf= 6, subsample= 0.6816427025399264, max_features = None)
}

results = []

for name, model in models.items():
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)



    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Precision_w': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred),
        'Recall_w': recall_score(y_test, y_pred, average='weighted'),
        'F1-Score': f1_score(y_test, y_pred),
        'F1-Score_w': f1_score(y_test, y_pred, average='weighted')
    })

results_df = pd.DataFrame(results)
print(results_df.round(4))

best_model = results_df.loc[results_df['F1-Score'].idxmax(), 'Model']
print(f"\nЛучшая модель по F1-Score: {best_model}")

                 Model  Accuracy  Precision  Precision_w  Recall  Recall_w  \
0  Logistic Regression    0.9893     0.9072       0.9888  0.7370    0.9893
1        Decision Tree    0.9900     0.9082       0.9896  0.7621    0.9900
2        Random Forest    0.9738     1.0000       0.9745  0.1725    0.9738
3    Gradient Boosting    0.9908     0.9029       0.9904  0.7940    0.9908

   F1-Score  F1-Score_w
0    0.8133      0.9888
1    0.8288      0.9896
2    0.2943      0.9648
3    0.8449      0.9905

Лучшая модель по F1-Score: Gradient Boosting

In [16]:
results_df

,Model,Accuracy,Precision,Precision_w,Recall,Recall_w,F1-Score,F1-Score_w
0,Logistic Regression,0.989300,0.907216,0.988800,0.737018,0.989300,0.813309,0.988763
1,Decision Tree,0.990042,0.908184,0.989614,0.762144,0.990042,0.828780,0.989620
2,Random Forest,0.973833,1.000000,0.974522,0.172529,0.973833,0.294286,0.964775
3,Gradient Boosting,0.990783,0.902857,0.990438,0.793970,0.990783,0.844920,0.990497