In [1]:
from pathlib import Path
import sys
import pandas as pd

sys.path.append(str(Path().resolve().parent))
from src.data_processing.data_processing import make_data_from_faculty, clean_data, make_data_from_program, make_features, process_data
from src.data_processing.data_processing import main as main_data

In [2]:
df_clean = main_data()

/mnt/d/ml_project/ml_project_2026/src/data_processing/data_processing.py:8: DtypeWarning: Columns (0: course, 1: module, 2: academic_year) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, sep = ';')

In [3]:
df_clean = clean_data(df_clean)
df_clean = process_data(df_clean)

In [4]:
df_clean['exam_type'].unique()

<StringArray>
[                     'Первая сдача',                         'Пересдача',
                  'Полный перезачет',             'Пересдача с комиссией',
 'Пересдача по уважительной причине',               'Частичный перезачет']
Length: 6, dtype: str

In [5]:
import statistics

def make_features_loc(df : pd.DataFrame) -> pd.DataFrame:
    result = []
    
    for student_id_hash, group in df.groupby('student_id_hash'):
        grades = group['grade_10'].tolist()
        avg_grade = sum(grades) / len(grades)

        
        student_status = group['student_status'].iloc[0]
        
        
        result.append({
            'student__id_hash': student_id_hash,
            'grades_list': grades,
            'avg_grade': avg_grade,
            'median_grade': statistics.median(grades),
            'min_grade': min(grades),
            'max_grade': max(grades),
            'count_grades': len(grades),
            # 'count_retake': len(group[group['exam_type'] == 'Пересдача']),
            'proportion_retake': len(group[group['exam_type'] == 'Пересдача'])/len(grades),
            # 'count_retake_com': len(group[group['exam_type'] == 'Пересдача с комиссией']),
            'proportion_retake_com': len(group[group['exam_type'] == 'Пересдача с комиссией'])/len(grades),
            'student_status': student_status

        })

    
    
    return pd.DataFrame(result)

df_encoded = make_features_loc(df_clean)

In [6]:
df_encoded['count_grades'].unique()
# print(df_encoded.loc[0].notna().sum())

# cols = [s for s in df_encoded.columns if '3_2' in s]


# df_encoded_part = df_encoded[cols]

array([ 24, 115,  14,  22,  16,  41,  18,  52,  12,  55,  15,  13,  21,
        58,   9,  50,  19,  32,  26,  17,  61,  35,  28,  40,  25,  34,
        11,   1,  65,  20,  38,  31,  10,   4,   8,  49,  39,   7,   6,
         3,  37,  62,  56,  51,  47,  29,  64,  57,  53,  33,  68,   5,
        27,   2,  42,  45,  59,  23,  54,  44,  43,  36,  63,  66,  30,
        60,  46,  98,  48,  70,  75,  91, 100,  69,  67,  72,  76,  77,
        74,  82,  73,  92,  71,  81, 109,  85, 107,  94, 126, 102,  93,
        96,  84,  90, 157, 121,  88, 149,  78,  80,  89,  83,  87,  95,
        79, 125, 118, 132, 154, 106, 104,  86,  97, 112, 111, 152, 114,
        99, 103, 131, 120, 113, 124, 108])

In [7]:
def str_to_int_stadent_status (df : pd.DataFrame):
    df["student_status"] = df["student_status"].map({
        "study": 0,
        "graduated": 1,
        "expelled": 2,
        "leave" : 3
    })
    return df

In [8]:
df_encoded = str_to_int_stadent_status(df_encoded)

In [9]:
df_encoded

,student__id_hash,grades_list,avg_grade,median_grade,min_grade,max_grade,count_grades,proportion_retake,proportion_retake_com,student_status
0,00000d86dad0d3c197341f776bb61a1d,"[10, 9, 10, 10, 10, 10, 7, 10, 8, 7, 8, 10, 10...",8.166667,9.0,2,10,24,0.000000,0.000000,1
1,0001dd443aff5c0800694730323c3d7d,"[8, 9, 7, 9, 8, 7, 9, 8, 7, 7, 8, 8, 7, 7, 7, ...",6.973913,7.0,0,10,115,0.034783,0.008696,0
2,00035b28bedc6d3a0336cb61a841d79b,"[8, 6, 5, 8, 6, 8, 9, 8, 7, 9, 7, 8, 8, 4]",7.214286,8.0,4,9,14,0.000000,0.000000,0
3,00044a704df898b9a87faf40795d62b6,"[8, 8, 9, 8, 9, 9, 8, 10, 10, 10, 7, 8, 9, 9, ...",8.454545,8.0,7,10,22,0.000000,0.000000,1
4,0004d03d5c41e468a521ed8a964fe889,"[6, 9, 8, 8, 7, 7, 9, 7, 8, 7, 9, 7, 8, 6, 3, 7]",7.250000,7.0,3,9,16,0.062500,0.000000,0
...,...,...,...,...,...,...,...,...,...,...
62925,fffaf96349866c4fbf94dca72aad6f0e,"[7, 7, 9, 7, 7, 4, 7, 7, 7, 7, 7, 4, 6, 6, 4, ...",6.709091,7.0,3,10,55,0.018182,0.000000,0
62926,fffbf91749bd6fd12d3ddf2ee81ee633,"[10, 8, 10, 7, 9, 8, 8, 9, 8, 8, 6, 8, 8, 8, 8...",8.238095,8.0,6,10,21,0.000000,0.000000,0
62927,fffc29ec23eda92a88df30e449afcf1c,"[6, 5, 7, 7, 10, 7, 8, 6, 6, 8, 8, 6, 4, 5, 7,...",6.520000,6.0,4,10,25,0.000000,0.000000,1
62928,fffe12fc2c520bcb03f1437defdc7ecf,"[8, 10, 9, 8, 8, 7, 7, 9, 10, 8, 7, 8, 8, 7, 6...",7.600000,8.0,5,10,25,0.000000,0.000000,1
62929,ffff7050cc8412d5a8d80191ae6ce3d2,"[10, 5, 9, 10, 10, 6, 8, 5, 4, 9, 8, 9, 8, 7, ...",7.094595,7.5,2,10,74,0.013514,0.000000,0

In [25]:
df_encoded_2 = df_encoded[df_encoded['count_grades'] > 100]

In [26]:
df_encoded_2

,student__id_hash,grades_list,avg_grade,median_grade,min_grade,max_grade,count_grades,proportion_retake,proportion_retake_com,student_status
1,0001dd443aff5c0800694730323c3d7d,"[8, 9, 7, 9, 8, 7, 9, 8, 7, 7, 8, 8, 7, 7, 7, ...",6.973913,7.0,0,10,115,0.034783,0.008696,0
6551,1a74ee5ba73ee149df33f12804fe4850,"[8, 5, 4, 4, 5, 4, 4, 4, 3, 9, 4, 5, 3, 1, 7, ...",6.477064,7.0,0,10,109,0.055046,0.018349,0
9715,2747b9445ab10af1884d28377a8449c8,"[9, 8, 7, 7, 7, 8, 8, 7, 6, 7, 7, 7, 10, 8, 8,...",7.429907,7.0,5,10,107,0.000000,0.000000,0
10363,29d370dae5d04c60e0ac85b2076da264,"[7, 9, 10, 8, 7, 9, 5, 5, 8, 8, 4, 8, 9, 10, 4...",7.420561,8.0,0,10,107,0.018692,0.000000,0
10385,29e73c47fac6a477a28807c2ec0bcad4,"[7, 7, 5, 6, 6, 6, 8, 5, 7, 8, 7, 8, 6, 7, 5, ...",6.515873,6.5,0,10,126,0.023810,0.000000,0
10939,2c535b509956040160fbe78654cd7556,"[3, 4, 4, 5, 6, 5, 5, 6, 8, 3, 6, 5, 5, 5, 6, ...",5.656863,6.0,2,9,102,0.068627,0.000000,0
13884,385ba73871bb93cee1188276f6c1fcb1,"[5, 5, 4, 9, 5, 7, 6, 9, 2, 8, 5, 7, 4, 7, 8, ...",5.636943,6.0,0,10,157,0.050955,0.019108,0
17479,46abf2e7cd4dd4fe20a1d104345fa192,"[7, 7, 7, 7, 6, 8, 7, 7, 7, 8, 8, 8, 5, 6, 5, ...",5.669421,6.0,0,10,121,0.074380,0.016529,0
20330,51fa6fd4677884c4da2480982bb94c6e,"[8, 4, 10, 4, 6, 6, 8, 6, 7, 6, 9, 7, 6, 8, 9,...",7.080537,7.0,1,10,149,0.006711,0.006711,0
21605,5736ee0b807b8d32dc44d7ead9cbbdcb,"[10, 10, 10, 8, 9, 8, 8, 2, 8, 6, 9, 6, 8, 7, ...",7.880952,8.0,0,10,126,0.015873,0.000000,0
24496,62f12435865af0a6b5f4aa9981b63b48,"[7, 8, 10, 8, 8, 7, 8, 8, 8, 7, 9, 8, 8, 7, 9,...",7.320000,8.0,0,10,125,0.016000,0.008000,0
28613,742efe8730523336ff09ae62b621aff0,"[8, 5, 9, 6, 8, 9, 4, 4, 5, 9, 9, 7, 7, 5, 7, ...",6.953271,7.0,3,10,107,0.009346,0.000000,0
29512,77fbeb8945b2eb02b86cac08bcaf7854,"[8, 8, 6, 5, 9, 8, 6, 7, 7, 5, 7, 6, 8, 8, 8, ...",7.666667,8.0,4,10,102,0.000000,0.000000,0
29781,79271aec45153bbe044bf02da3ffda6f,"[6, 8, 7, 7, 9, 7, 7, 6, 8, 7, 9, 8, 9, 8, 9, ...",7.296610,7.0,0,10,118,0.000000,0.000000,0
30067,7a5c3f571484779109c2cbbeca496c26,"[4, 5, 4, 5, 6, 6, 4, 4, 4, 5, 6, 6, 6, 5, 5, ...",4.780303,5.0,0,10,132,0.090909,0.053030,0
32162,82efb84a5704c2714fd3d20291b74093,"[8, 9, 7, 4, 3, 9, 9, 8, 5, 6, 4, 7, 6, 8, 8, ...",6.727273,7.0,0,10,154,0.025974,0.000000,0
32168,82f23eabf03d6d7733041a722d60b02a,"[8, 6, 8, 7, 8, 8, 9, 5, 8, 9, 9, 8, 7, 6, 10,...",7.226415,7.0,2,10,106,0.018868,0.000000,0
32995,8656dd7a90cbd40140ead4aba85c0813,"[6, 6, 7, 6, 6, 6, 9, 8, 8, 8, 6, 6, 8, 0, 6, ...",6.528846,7.0,0,9,104,0.038462,0.000000,0
34929,8e397c17ce74c96cc09b96c383b04259,"[0, 7, 0, 8, 8, 9, 7, 8, 8, 8, 8, 10, 0, 5, 10...",7.616071,8.0,0,10,112,0.026786,0.000000,1
35543,90b28fa08a1b1f0e7d4c5787c652e96d,"[5, 4, 5, 8, 6, 4, 8, 4, 8, 9, 5, 5, 7, 6, 6, ...",6.513514,7.0,0,10,111,0.036036,0.018018,0
37931,9a4948bb095a8658fd4b37380ee8526f,"[10, 10, 10, 9, 9, 8, 8, 9, 9, 8, 8, 8, 9, 9, ...",8.119266,8.0,0,10,109,0.027523,0.000000,0
40580,a5413e3f0efda49e87768630f76f6f44,"[9, 9, 8, 8, 9, 9, 6, 7, 8, 9, 6, 5, 7, 9, 9, ...",7.756579,8.0,2,10,152,0.013158,0.000000,0
41990,ab1e5b0fce60eac5d9b68ef3a3f1bb22,"[8, 10, 8, 10, 7, 9, 10, 9, 8, 9, 9, 8, 8, 8, ...",7.271930,8.0,2,10,114,0.035088,0.000000,0
44987,b738309903714f02b6bfe1f52a4aff0e,"[8, 8, 8, 4, 7, 7, 6, 7, 9, 6, 9, 9, 8, 9, 9, ...",7.298077,7.5,0,10,104,0.009615,0.000000,0
45044,b7708870b42b378ea74a7fed9e567143,"[9, 8, 9, 10, 7, 10, 8, 9, 8, 9, 6, 9, 8, 9, 7...",8.233010,8.0,5,10,103,0.000000,0.000000,0
45271,b8430bbaf18c4efe66d2e5244983a852,"[8, 7, 8, 8, 10, 7, 7, 7, 10, 5, 4, 8, 7, 9, 9...",7.243243,7.0,4,10,111,0.000000,0.000000,0
45464,b8e8517c56a72a5cdf137967d249290a,"[10, 9, 10, 8, 9, 8, 10, 9, 10, 9, 8, 8, 8, 8,...",8.533898,9.0,5,10,118,0.000000,0.000000,0
46296,bc626e363132011d904cec74977364fa,"[10, 9, 5, 9, 8, 7, 9, 9, 9, 5, 10, 4, 8, 9, 9...",7.384615,8.0,4,10,104,0.000000,0.000000,0
47999,c30fdfeefc5bde4eb36551882149e78f,"[8, 8, 7, 7, 8, 8, 8, 8, 8, 8, 9, 8, 8, 7, 8, ...",7.641221,8.0,5,10,131,0.000000,0.000000,0
49880,cac57b0b7d077e40dff0cd4c0af9b5c5,"[8, 8, 8, 9, 7, 5, 9, 9, 10, 9, 10, 9, 7, 8, 8...",8.083333,8.0,3,10,132,0.007576,0.000000,0
50464,cd331d62a8295997b4fd567085a68a7b,"[7, 4, 5, 8, 0, 10, 5, 6, 8, 10, 9, 8, 8, 6, 5...",6.446602,7.0,0,10,103,0.058252,0.029126,0
51037,cf86efdaa75a2d3abbb014bed67ecc31,"[10, 9, 8, 8, 7, 9, 8, 6, 6, 8, 9, 9, 8, 8, 7,...",7.758333,8.0,0,10,120,0.008333,0.000000,0
53798,dadf51709e1817d350306f3e8c03680c,"[9, 7, 7, 7, 9, 7, 9, 9, 10, 0, 7, 0, 8, 9, 9,...",6.814159,7.0,0,10,113,0.026549,0.000000,0
55620,e2579394339ad882ccb8e10df4cc67f8,"[10, 9, 8, 8, 7, 7, 8, 9, 8, 10, 8, 10, 10, 10...",8.432203,9.0,4,10,118,0.000000,0.000000,0
57320,e98fd8a34006224d1f50361c47fe55cb,"[7, 10, 8, 9, 7, 9, 0, 7, 9, 9, 9, 10, 8, 6, 7...",7.879032,8.0,0,10,124,0.016129,0.000000,0
60529,f64dada443cd3d06b6b00fe74e838479,"[8, 0, 10, 9, 7, 6, 5, 4, 0, 8, 3, 5, 7, 7, 6,...",6.157407,7.0,0,10,108,0.055556,0.000000,0
61261,f950a4159b21613f9c7454bc4244cc71,"[8, 6, 6, 5, 7, 9, 8, 7, 8, 8, 8, 6, 6, 0, 9, ...",7.242718,7.0,0,10,103,0.009709,0.000000,0

сделать тренд оценок (разница оценок)   
количество несдавших эту же дисциплину в его группе

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [13]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.8.0
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License-Expression: BSD-3-Clause
Location: /mnt/d/ml_project/ml_project_2026/.venv/lib/python3.12/site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by:

In [27]:
X = df_encoded.drop(columns=['student__id_hash', 'grades_list', 'student_status'])
y = df_encoded['student_status']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)


model = LogisticRegression(solver='lbfgs', max_iter=10000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print (accuracy_score(y_test, y_pred))

print(precision_score(y_test, y_pred, average='macro'))

0.6435722231050374
0.49094224881505527

/mnt/d/ml_project/ml_project_2026/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])