In [2]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np

sys.path.append(str(Path().resolve().parent))
import src.data_processing.data_processing_copy as dp

In [13]:
df = dp.load_data('../data/raw/grades.csv')

/home/uliana/project/ml_project_2026/src/data_processing/data_processing_copy.py:8: DtypeWarning: Columns (0: course, 1: module, 2: academic_year) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, sep = ';')

In [8]:
df

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,subject_unit,grade_10,absence_status,module,academic_year,student_status
0,657b2a6069af97615b4c82205863561b,Москва,факультет экономических наук,Финансовый инжиниринг,Магистратура,2,МФИИН231,Коммерческие,Дисциплина: Финансовые рынки: проблемы и решения,Первая сдача,М_ФРПИР_П_676572_1,6,\N,1,2024,graduated
1,394b76e0ea7739201d39f8c139808de3,Москва,Высшая школа бизнеса,Управление бизнесом,Бакалавриат,4,БМБ2102,Коммерческие,Дисциплина: Управление организационной жизнест...,Первая сдача,М_УОЖ_Г_909498_2,7,\N,1,2024,graduated
2,a6b5e298d01156513fec7056f21313c5,Москва,факультет права,Юрист в правосудии,Магистратура,2,МЮП231,Бюджетные,Дисциплина: Отбор и назначение судей,Первая сдача,М_ОИНС_Г_800881_1,8,\N,1,2024,graduated
3,592333b03350965546a17ae33cd4d3d8,Москва,факультет права,Юрист в бизнесе,Магистратура,2,МЮБ232,Коммерческие,Дисциплина: Экономический анализ права,Первая сдача,М_ЭАП_П_787475_1,8,\N,1,2024,graduated
4,871132d017f31ba4bf97371ac228c638,Москва,факультет мировой экономики и мировой политики,Экономика окружающей среды и устойчивое развитие,Магистратура,2,МЭОС231,Коммерческие места для иностранных граждан,Научно-исследовательский семинар: Семинар наст...,Первая сдача,М_СНЭОСИУР_Г_735356_1,5,\N,1,2024,graduated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767981,795701eee90e3518d3fe68c457bf7bcc,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,\N,10,\N,\N,\N,graduated
1767982,e099c58e677873c9de640fdba8ffd81e,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа социальных...,Современный социальный анализ,Магистратура,2,МСА221С,Бюджетные,Дисциплина: Моделирование структурными уравнен...,Пересдача по уважительной причине,С_МСУ_Г_406655_1,10,\N,\N,\N,graduated
1767983,652e310bf0efc60fd20688731547c4c7,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,\N,10,\N,\N,\N,graduated
1767984,9768029158169935cbda39d9cb4ccbdf,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Коммерческие,Дисциплина: Современные методы и инструменты у...,Первая сдача,\N,8,\N,\N,\N,graduated
1767985,3e1d58c3557de4a82a8b6e92edbe6756,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,\N,10,\N,\N,\N,graduated

In [ ]:
# df = dp.load_data('../data/raw/grades.csv')
dp.validate_data(df)
df = dp.clean_data(df)
# df = dp.process_data(df)
df

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,subject_unit,grade_10,absence_status,module,academic_year,student_status
0,657b2a6069af97615b4c82205863561b,Москва,факультет экономических наук,Финансовый инжиниринг,Магистратура,2,МФИИН231,Коммерческие,Дисциплина: Финансовые рынки: проблемы и решения,Первая сдача,М_ФРПИР_П_676572_1,6,NaN,1,2024,graduated
1,394b76e0ea7739201d39f8c139808de3,Москва,Высшая школа бизнеса,Управление бизнесом,Бакалавриат,4,БМБ2102,Коммерческие,Дисциплина: Управление организационной жизнест...,Первая сдача,М_УОЖ_Г_909498_2,7,NaN,1,2024,graduated
2,a6b5e298d01156513fec7056f21313c5,Москва,факультет права,Юрист в правосудии,Магистратура,2,МЮП231,Бюджетные,Дисциплина: Отбор и назначение судей,Первая сдача,М_ОИНС_Г_800881_1,8,NaN,1,2024,graduated
3,592333b03350965546a17ae33cd4d3d8,Москва,факультет права,Юрист в бизнесе,Магистратура,2,МЮБ232,Коммерческие,Дисциплина: Экономический анализ права,Первая сдача,М_ЭАП_П_787475_1,8,NaN,1,2024,graduated
4,871132d017f31ba4bf97371ac228c638,Москва,факультет мировой экономики и мировой политики,Экономика окружающей среды и устойчивое развитие,Магистратура,2,МЭОС231,Коммерческие места для иностранных граждан,Научно-исследовательский семинар: Семинар наст...,Первая сдача,М_СНЭОСИУР_Г_735356_1,5,NaN,1,2024,graduated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767981,795701eee90e3518d3fe68c457bf7bcc,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,NaN,10,NaN,NaN,NaN,graduated
1767982,e099c58e677873c9de640fdba8ffd81e,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа социальных...,Современный социальный анализ,Магистратура,2,МСА221С,Бюджетные,Дисциплина: Моделирование структурными уравнен...,Пересдача по уважительной причине,С_МСУ_Г_406655_1,10,NaN,NaN,NaN,graduated
1767983,652e310bf0efc60fd20688731547c4c7,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,NaN,10,NaN,NaN,NaN,graduated
1767984,9768029158169935cbda39d9cb4ccbdf,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Коммерческие,Дисциплина: Современные методы и инструменты у...,Первая сдача,NaN,8,NaN,NaN,NaN,graduated
1767985,3e1d58c3557de4a82a8b6e92edbe6756,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,NaN,10,NaN,NaN,NaN,graduated

In [10]:
df = dp.process_data(df)

In [ ]:
def process_data(df: pd.DataFrame) -> pd.DataFrame:
    inconsistent = df.groupby('student_id_hash')['student_status'].nunique()
    bad_ids = inconsistent[inconsistent > 1].index
    df_clean = df[~df['student_id_hash'].isin(bad_ids)]
    

    df_clean = df_clean.drop(columns=['subject_unit'])
    # df_clean= df_clean.dropna()

    # students_info = df_clean[['student_id_hash', 'campus', 'group', 'faculty', 'place_type', 'program','education_level', 'student_status' ]].copy()
    

    return df_clean

In [14]:
df = process_data(df)
df

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,grade_10,absence_status,module,academic_year,student_status
0,657b2a6069af97615b4c82205863561b,Москва,факультет экономических наук,Финансовый инжиниринг,Магистратура,2,МФИИН231,Коммерческие,Дисциплина: Финансовые рынки: проблемы и решения,Первая сдача,6,\N,1,2024,graduated
1,394b76e0ea7739201d39f8c139808de3,Москва,Высшая школа бизнеса,Управление бизнесом,Бакалавриат,4,БМБ2102,Коммерческие,Дисциплина: Управление организационной жизнест...,Первая сдача,7,\N,1,2024,graduated
2,a6b5e298d01156513fec7056f21313c5,Москва,факультет права,Юрист в правосудии,Магистратура,2,МЮП231,Бюджетные,Дисциплина: Отбор и назначение судей,Первая сдача,8,\N,1,2024,graduated
3,592333b03350965546a17ae33cd4d3d8,Москва,факультет права,Юрист в бизнесе,Магистратура,2,МЮБ232,Коммерческие,Дисциплина: Экономический анализ права,Первая сдача,8,\N,1,2024,graduated
4,871132d017f31ba4bf97371ac228c638,Москва,факультет мировой экономики и мировой политики,Экономика окружающей среды и устойчивое развитие,Магистратура,2,МЭОС231,Коммерческие места для иностранных граждан,Научно-исследовательский семинар: Семинар наст...,Первая сдача,5,\N,1,2024,graduated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767981,795701eee90e3518d3fe68c457bf7bcc,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,10,\N,\N,\N,graduated
1767982,e099c58e677873c9de640fdba8ffd81e,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа социальных...,Современный социальный анализ,Магистратура,2,МСА221С,Бюджетные,Дисциплина: Моделирование структурными уравнен...,Пересдача по уважительной причине,10,\N,\N,\N,graduated
1767983,652e310bf0efc60fd20688731547c4c7,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,10,\N,\N,\N,graduated
1767984,9768029158169935cbda39d9cb4ccbdf,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Коммерческие,Дисциплина: Современные методы и инструменты у...,Первая сдача,8,\N,\N,\N,graduated
1767985,3e1d58c3557de4a82a8b6e92edbe6756,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты у...,Первая сдача,10,\N,\N,\N,graduated

In [ ]:
df["attempt_score"] = df["exam_type"].map({
    "Первая сдача": 0,
    "Пересдача": 1,
    "Пересдача по уважительной причине": 0,
    "Пересдача с комиссией": 2
})
df

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,grade_10,absence_status,module,academic_year,student_status,attempt_score
50,3a9996bc6bc1416b0a35a36b091baf6f,Москва,Высшая школа бизнеса,Управление людьми: цифровые технологии и орган...,Магистратура,2,МУЛЦТ231,Коммерческие,Дисциплина: Управление вознаграждением и социа...,Первая сдача,0,invalid,1,2024,graduated,0
63,02da67f39300f728e95474831012fd4b,Москва,факультет гуманитарных наук,Компьютерная лингвистика,Магистратура,2,МКЛ221,Бюджетные,Дисциплина: Социальные сети,Первая сдача,5,invalid,1,2024,graduated,0
74,fed0cae566877b6b72e39df0c6018dc4,Москва,факультет креативных индустрий,"Коммуникации, основанные на данных",Магистратура,2,МКОНД231,Коммерческие,Научно-исследовательский семинар: Проектный се...,Первая сдача,0,valid,1,2024,graduated,0
260,3ae3aab8c6a5e0f863713288756fed8d,Москва,Высшая школа бизнеса,Управление устойчивым развитием компании,Магистратура,2,МУУРК231,Коммерческие,Дисциплина: Устойчивое предпринимательство и б...,Первая сдача,0,valid,1,2024,graduated,0
316,fa81c1c712378cdc7b83c4397b549cf0,Москва,Высшая школа бизнеса,Управление людьми: цифровые технологии и орган...,Магистратура,2,МУЛЦТ231,Коммерческие,Дисциплина: Управление стратегическими коммуни...,Первая сдача,0,valid,1,2024,graduated,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744816,5188fcfd6fdbbe565e7ebd2b8e9f7807,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Цифровые платформы и логистика,Бакалавриат,4,БЦП221С,Коммерческие,Дисциплина: Математический анализ II,Пересдача по уважительной причине,1,invalid,4,2022,study,0
1744827,79dee9e3244b3ed48d74c85be806d306,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Цифровые платформы и логистика,Бакалавриат,4,БЦП221С,Коммерческие места для иностранных граждан,Дисциплина: Математический анализ II,Первая сдача,3,valid,4,2022,study,0
1744830,45e64ed894f88f0e1ae7eceb11e1a5d2,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Цифровые платформы и логистика,Бакалавриат,4,БЦП221С,Коммерческие,Дисциплина: Математический анализ II,Пересдача,1,invalid,4,2022,study,1
1744838,4bb0d74689ebe2d21a18298ddeaf7772,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Цифровые платформы и логистика,Бакалавриат,4,БЦП221С,Коммерческие,Дисциплина: Математический анализ II,Первая сдача,1,valid,4,2022,study,0
1744882,442d9cc222307c2f5e2d5e7df53d7f5a,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа гуманитарн...,Филология,Бакалавриат,4,БФЛ223С,Бюджетные,Дисциплина: Введение в языкознание,Первая сдача,5,valid,4,2022,study,0

In [5]:
df.drop("exam_type", axis=1)
len(df[df['grade_10'] == 0])/len(df)

0.5552478451628964

In [ ]:
def make_data_from_faculty(df : pd.DataFrame, faculty: str, addictional_columns: list) -> None:
    df_baseline = df[df['faculty'] == faculty]
    
    
    
    df_baseline_encoded = df_baseline.pivot_table(
        index='student_id_hash',
        columns=['course', 'module', 'subject_name'],
        values='grade_10',
        aggfunc = 'mean'
    )

    df_baseline_encoded.columns = [
        "_".join(map(str, col)).strip()
        for col in df_baseline_encoded.columns
    ]
    df_baseline_encoded = df_baseline_encoded.reset_index()

    df_baseline_encoded = df_baseline_encoded.merge(
        df_baseline[['student_id_hash'] + addictional_columns],
        on='student_id_hash',
        how='left'
    )
    df_baseline_encoded = df_baseline_encoded.drop_duplicates()
    return df_baseline_encoded

In [25]:
new_df = make_data_from_faculty(df, "факультет права", ['attempt_score', 'student_status'])
# df = dp.str_to_int_stadent_status(df)
new_df

,student_id_hash,1_2_Дисциплина: Актуальные проблемы вещного права,1_2_Дисциплина: Английский язык для общих академических целей. Продвинутый курс - 1,1_2_Дисциплина: История России,1_2_Дисциплина: История государства и права зарубежных стран,1_2_Дисциплина: Корпоративное право,1_2_Дисциплина: Основы программирования на Python,1_2_Дисциплина: Предпринимательское право - 2,1_2_Дисциплина: Теория международного права и современные проблемы международного экономического права,"1_2_Научно-исследовательский семинар: Научно-исследовательский семинар ""Информационные технологии в деятельности юриста""",...,5_4_Дисциплина: Предпринимательское право,5_4_Дисциплина: Прикладная информатика в юриспруденции,5_4_Дисциплина: Профессии в арт-мире,5_4_Дисциплина: Уголовно-процессуальное право,5_4_Дисциплина: Уголовное право (общая часть),5_4_Дисциплина: Управление продуктом,5_4_Дисциплина: Цифровые технологии в правотворческой деятельности,6_2_Выпускная квалификационная работа: Защита выпускной квалификационной работы,attempt_score,student_status
0,00470ec645825c67b00395a745ac9ea4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,graduated
1,0065af051b602daa5d3d35f4ca4e7681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,study
2,00c2258d560dffb74baa8740a34668a0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,expelled
3,010481e740864b8a8df1e9840032f4e7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,graduated
4,0133a145f7499ac5cc8de7a4a8f9d245,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,expelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,ffcaa30fa824f0f7f90842f4ad4e1291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,expelled
933,ffcaa30fa824f0f7f90842f4ad4e1291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,expelled
934,ffd69c30f929bbf238d0ef9d039319c7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,graduated
936,ffe01132a5ab3062dc950aa77e4aba24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,expelled
942,ffe0f2f673d4d76cd86bb5f044ecbb50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,study

In [26]:
new_df[new_df["student_id_hash"] == "00470ec645825c67b00395a745ac9ea4"]

,student_id_hash,1_2_Дисциплина: Актуальные проблемы вещного права,1_2_Дисциплина: Английский язык для общих академических целей. Продвинутый курс - 1,1_2_Дисциплина: История России,1_2_Дисциплина: История государства и права зарубежных стран,1_2_Дисциплина: Корпоративное право,1_2_Дисциплина: Основы программирования на Python,1_2_Дисциплина: Предпринимательское право - 2,1_2_Дисциплина: Теория международного права и современные проблемы международного экономического права,"1_2_Научно-исследовательский семинар: Научно-исследовательский семинар ""Информационные технологии в деятельности юриста""",...,5_4_Дисциплина: Предпринимательское право,5_4_Дисциплина: Прикладная информатика в юриспруденции,5_4_Дисциплина: Профессии в арт-мире,5_4_Дисциплина: Уголовно-процессуальное право,5_4_Дисциплина: Уголовное право (общая часть),5_4_Дисциплина: Управление продуктом,5_4_Дисциплина: Цифровые технологии в правотворческой деятельности,6_2_Выпускная квалификационная работа: Защита выпускной квалификационной работы,attempt_score,student_status
0,00470ec645825c67b00395a745ac9ea4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,graduated