In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('grades.csv', sep = ';')
df.head()

/tmp/ipykernel_11104/3791768520.py:1: DtypeWarning: Columns (0: course, 1: module, 2: academic_year) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('grades.csv', sep = ';')

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,subject_unit,grade_10,absence_status,module,academic_year,student_status
0,657b2a6069af97615b4c82205863561b,Москва,факультет экономических наук,Финансовый инжиниринг,Магистратура,2,МФИИН231,Коммерческие,Дисциплина: Финансовые рынки: проблемы и решения,Первая сдача,М_ФРПИР_П_676572_1,6,\N,1,2024,graduated
1,394b76e0ea7739201d39f8c139808de3,Москва,Высшая школа бизнеса,Управление бизнесом,Бакалавриат,4,БМБ2102,Коммерческие,Дисциплина: Управление организационной жизнест...,Первая сдача,М_УОЖ_Г_909498_2,7,\N,1,2024,graduated
2,a6b5e298d01156513fec7056f21313c5,Москва,факультет права,Юрист в правосудии,Магистратура,2,МЮП231,Бюджетные,Дисциплина: Отбор и назначение судей,Первая сдача,М_ОИНС_Г_800881_1,8,\N,1,2024,graduated
3,592333b03350965546a17ae33cd4d3d8,Москва,факультет права,Юрист в бизнесе,Магистратура,2,МЮБ232,Коммерческие,Дисциплина: Экономический анализ права,Первая сдача,М_ЭАП_П_787475_1,8,\N,1,2024,graduated
4,871132d017f31ba4bf97371ac228c638,Москва,факультет мировой экономики и мировой политики,Экономика окружающей среды и устойчивое развитие,Магистратура,2,МЭОС231,Коммерческие места для иностранных граждан,Научно-исследовательский семинар: Семинар наст...,Первая сдача,М_СНЭОСИУР_Г_735356_1,5,\N,1,2024,graduated

In [17]:
df[df["absence_status"] != "\\N"]

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,subject_unit,grade_10,absence_status,module,academic_year,student_status
50,3a9996bc6bc1416b0a35a36b091baf6f,Москва,Высшая школа бизнеса,Управление людьми: цифровые технологии и орган...,Магистратура,2,МУЛЦТ231,Коммерческие,Дисциплина: Управление вознаграждением и социа...,Первая сдача,М_УВИСЛ_Г_863134_1,0,invalid,1,2024,graduated
63,02da67f39300f728e95474831012fd4b,Москва,факультет гуманитарных наук,Компьютерная лингвистика,Магистратура,2,МКЛ221,Бюджетные,Дисциплина: Социальные сети,Первая сдача,М_СС_Г_688688_1,5,invalid,1,2024,graduated
74,fed0cae566877b6b72e39df0c6018dc4,Москва,факультет креативных индустрий,"Коммуникации, основанные на данных",Магистратура,2,МКОНД231,Коммерческие,Научно-исследовательский семинар: Проектный се...,Первая сдача,М_ПСМВСA_Г_786358_1,0,valid,1,2024,graduated
260,3ae3aab8c6a5e0f863713288756fed8d,Москва,Высшая школа бизнеса,Управление устойчивым развитием компании,Магистратура,2,МУУРК231,Коммерческие,Дисциплина: Устойчивое предпринимательство и б...,Первая сдача,М_УПИБ_Г_866065_1,0,valid,1,2024,graduated
316,fa81c1c712378cdc7b83c4397b549cf0,Москва,Высшая школа бизнеса,Управление людьми: цифровые технологии и орган...,Магистратура,2,МУЛЦТ231,Коммерческие,Дисциплина: Управление стратегическими коммуни...,Первая сдача,М_УСК_Г_909021_1,0,valid,1,2024,graduated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767649,e45c9834de3fdd50f9ec17640f05a388,Москва,Международный институт экономики и финансов,Международная программа по экономике и финансам,Бакалавриат,2,БМПЭФ249,Коммерческие,Дисциплина: История России,Первая сдача,М_ИР_П_790309_2,1,valid,\N,\N,expelled
1767674,e45c9834de3fdd50f9ec17640f05a388,Москва,Международный институт экономики и финансов,Международная программа по экономике и финансам,Бакалавриат,2,БМПЭФ249,Коммерческие,Дисциплина: Теория вероятностей и статистика,Первая сдача,М_ТВИС_П_789936_2,0,valid,\N,\N,expelled
1767884,2fa062ff404ef41fa1599a4be017f2b6,НИУ ВШЭ - Нижний Новгород,"Факультет информатики, математики и компьютерн...",Прикладная математика и информатика,Бакалавриат,4,21 ПМИ-2,Коммерческие места для иностранных граждан,Дисциплина: Исследование операций,Пересдача с комиссией,Н_ИО_П_452218_1,0,invalid,\N,\N,graduated
1767917,bf6430fe33d178760567e0f36bb4a2db,НИУ ВШЭ - Нижний Новгород,Факультет экономики,Экономика,Бакалавриат,3,21Э3,Коммерческие,Дисциплина: Налогообложение физических и юриди...,Первая сдача,Н_НФИЮЛ_П_646663_1,0,valid,\N,\N,expelled
1767971,1dff9f54def2e4fd58cd8b778d1c66f2,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики ...,Стратегическое управление логистикой и цепями ...,Магистратура,1,МСУЛЦП232С,Коммерческие,Дисциплина: Современные методы и инструменты у...,Первая сдача,\N,0,invalid,\N,\N,expelled

In [22]:
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.width', 200)

table = []
for column in df.columns[1:]:
    table.append(df[column].unique())

table_df = pd.DataFrame({
    'columns' : df.columns[1:],
    'unique values' : table
})

table_df

            columns                                                                                        unique values
0            campus                  [Москва, НИУ ВШЭ - Нижний Новгород, НИУ ВШЭ - Пермь, НИУ ВШЭ - Санкт-Петербург, \N]
1           faculty  [факультет экономических наук, Высшая школа бизнеса, факультет права, факультет мировой экономик...
2           program  [Финансовый инжиниринг, Управление бизнесом, Юрист в правосудии, Юрист в бизнесе, Экономика окру...
3   education_level                                                             [Магистратура, Бакалавриат, Специалитет]
4            course                                                             [2, 4, 3, 5, 6, 1, 2, 4, 3, 1, 5, 6, \N]
5             group  [МФИИН231, БМБ2102, МЮП231, МЮБ232, МЭОС231, ММД231, МИНЯЗ231, МДРОБ232, СМК233, ММРЭК231, МУЛЦТ...
6        place_type  [Коммерческие, Бюджетные, Коммерческие места для иностранных граждан, По межправительственным со...
7      subject_name  [Дисциплина: Финансовые рынки: проблемы и решения, Дисциплина: Управление организационной жизнес...
8         exam_type  [Первая сдача, Пересдача, Полный перезачет, Пересдача с комиссией, Пересдача по уважительной при...
9      subject_unit  [М_ФРПИР_П_676572_1, М_УОЖ_Г_909498_2, М_ОИНС_Г_800881_1, М_ЭАП_П_787475_1, М_СНЭОСИУР_Г_735356_...
10         grade_10                                                               [6, 7, 8, 5, 9, 10, 4, 2, \N, 0, 3, 1]
11   absence_status                                                                        [\N, invalid, valid, medical]
12           module                                                                                  [1, 2, 3, 4, 4, \N]
13    academic_year                                                                         [2024, 2023, 2022, 2022, \N]
14   student_status                                                                  [graduated, study, expelled, leave]

In [ ]:
table_df.to_csv('unique_values.csv', index=False, encoding='utf-8')

In [29]:
df.replace({'\\N' : np.nan, '0' : 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, '2022' : 2022}, inplace=True)

,student_id_hash,campus,faculty,program,education_level,course,group,place_type,subject_name,exam_type,subject_unit,grade_10,absence_status,module,academic_year,student_status
0,657b2a6069af97615b4c82205863561b,Москва,факультет экономических наук,Финансовый инжиниринг,Магистратура,2,МФИИН231,Коммерческие,Дисциплина: Финансовые рынки: проблемы и решения,Первая сдача,М_ФРПИР_П_676572_1,6,NaN,1,2024,graduated
1,394b76e0ea7739201d39f8c139808de3,Москва,Высшая школа бизнеса,Управление бизнесом,Бакалавриат,4,БМБ2102,Коммерческие,Дисциплина: Управление организационной жизнестойкостью,Первая сдача,М_УОЖ_Г_909498_2,7,NaN,1,2024,graduated
2,a6b5e298d01156513fec7056f21313c5,Москва,факультет права,Юрист в правосудии,Магистратура,2,МЮП231,Бюджетные,Дисциплина: Отбор и назначение судей,Первая сдача,М_ОИНС_Г_800881_1,8,NaN,1,2024,graduated
3,592333b03350965546a17ae33cd4d3d8,Москва,факультет права,Юрист в бизнесе,Магистратура,2,МЮБ232,Коммерческие,Дисциплина: Экономический анализ права,Первая сдача,М_ЭАП_П_787475_1,8,NaN,1,2024,graduated
4,871132d017f31ba4bf97371ac228c638,Москва,факультет мировой экономики и мировой политики,Экономика окружающей среды и устойчивое развитие,Магистратура,2,МЭОС231,Коммерческие места для иностранных граждан,"Научно-исследовательский семинар: Семинар наставника ""Экономика окружающей среды и устойчивое ра...",Первая сдача,М_СНЭОСИУР_Г_735356_1,5,NaN,1,2024,graduated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767981,795701eee90e3518d3fe68c457bf7bcc,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики и менеджмента Национального исследовательского уни...,Стратегическое управление логистикой и цепями поставок,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты управления проектами,Первая сдача,NaN,10,NaN,NaN,NaN,graduated
1767982,e099c58e677873c9de640fdba8ffd81e,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа социальных наук,Современный социальный анализ,Магистратура,2,МСА221С,Бюджетные,Дисциплина: Моделирование структурными уравнениями,Пересдача по уважительной причине,С_МСУ_Г_406655_1,10,NaN,NaN,NaN,graduated
1767983,652e310bf0efc60fd20688731547c4c7,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики и менеджмента Национального исследовательского уни...,Стратегическое управление логистикой и цепями поставок,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты управления проектами,Первая сдача,NaN,10,NaN,NaN,NaN,graduated
1767984,9768029158169935cbda39d9cb4ccbdf,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики и менеджмента Национального исследовательского уни...,Стратегическое управление логистикой и цепями поставок,Магистратура,2,МСУЛЦП232С,Коммерческие,Дисциплина: Современные методы и инструменты управления проектами,Первая сдача,NaN,8,NaN,NaN,NaN,graduated
1767985,3e1d58c3557de4a82a8b6e92edbe6756,НИУ ВШЭ - Санкт-Петербург,факультет Санкт-Петербургская школа экономики и менеджмента Национального исследовательского уни...,Стратегическое управление логистикой и цепями поставок,Магистратура,2,МСУЛЦП232С,Бюджетные,Дисциплина: Современные методы и инструменты управления проектами,Первая сдача,NaN,10,NaN,NaN,NaN,graduated

In [30]:
for column in df.columns[1:]:
    print(f"Столбец '{column}':")
    print(df[column].unique())

Столбец 'campus':
<StringArray>
['Москва', 'НИУ ВШЭ - Нижний Новгород', 'НИУ ВШЭ - Пермь', 'НИУ ВШЭ - Санкт-Петербург', nan]
Length: 5, dtype: str
Столбец 'faculty':
<StringArray>
[                                                                                                      'факультет экономических наук',
                                                                                                               'Высшая школа бизнеса',
                                                                                                                    'факультет права',
                                                                                     'факультет мировой экономики и мировой политики',
                                                                                                     'факультет креативных индустрий',
                                                                                                           'Школа иностранных языков',
                                                                                                               'Институт образования',
                                                                                      'факультет городского и регионального развития',
                                                                                     'Высшая школа юриспруденции и администрирования',
                                                                                                        'факультет компьютерных наук',
                                                                     'Московский институт электроники и математики им. А.Н. Тихонова',
                                                                                                          'факультет социальных наук',
                                                                                                        'факультет гуманитарных наук',
                                                                                                                   'факультет физики',
                                                                                                                'Банковский институт',
                                                                                             'Школа инноватики и предпринимательства',
                                                                                                     'Институт когнитивных нейронаук',
                                                                                        'Международный институт экономики и финансов',
                                                                                                                    'факультет химии',
                                                                                                         'Институт торговой политики',
                                                                                                 'факультет биологии и биотехнологии',
                                                                                 'факультет географии и геоинформационных технологий',
                                                                          'М Институт статистических исследований и экономики знаний',
                                                                                                      'Институт проблем безопасности',
                                                                                                               'факультет математики',
                                                                                                              'Факультет менеджмента',
                                                                                                                'Факультет экономики',
                                                                              'Факультет информатики, математики и компьютерных наук',
                                                                                                        'Факультет гуманитарных наук',
                                                                                                                    'Факультет права',
                                                                              'Факультет социально-экономических и компьютерных наук',
                                                                                                                 'Магистерская школа',
                                                                                   'Вечерне-заочный факультет экономики и управления',
 'факультет Санкт-Петербургская школа экономики и менеджмента Национального исследовательского университета «Высшая школа экономики»',
                                                                                        'факультет Санкт-Петербургская школа дизайна',
                                                                                                              'юридический факультет',
                                                      'факультет Санкт-Петербургская школа физико-математических и компьютерных наук',
                                                                                            'Институт востоковедения и африканистики',
                                                                                'факультет Санкт-Петербургская школа социальных наук',
                                                                   'факультет Санкт-Петербургская школа гуманитарных наук и искусств',
                                                                                 'факультет "Школа информатики, физики и технологий"',
                                                                                                                                  nan,
                                                                                     'Международный центр управления цепями поставок',
                                                               'Факультет Санкт-Петербургская школа социальных наук и востоковедения',
                                                                               'Базовая кафедра Музея современного искусства "Гараж"',
                                                                              'центр развития компетенций в области финансов и учета',
                                                                   'М институт профессиональной переподготовки специалистов 202203FC',
                                                                            'П Факультет экономики, менеджмента и бизнес-информатики',
                                                                             'Международная лаборатория прикладного сетевого анализа']
Length: 49, dtype: str
Столбец 'program':
<StringArray>
[                                                                                    'Финансовый инжиниринг',
                                                                                       'Управление бизнесом',
                                                                                        'Юрист в правосудии',
                                                                                           'Юрист в бизнесе',
                                                          'Экономика окружающей среды и устойчивое развитие',
                                                                                           'Медиаменеджмент',
                                                            'Иностранные языки и межкультурная коммуникация',
                                                                        'Доказательное развитие образования',
                                                                    'Стратегический менеджмент и консалтинг',
                                                                                         'Мировая экономика',
 ...
                                                                                             'Частное право',
                                    'Экономика впечатлений: менеджмент в индустрии гостеприимства и туризме',
                                                                 'Экономика и инженерия транспортных систем',
                                                        'Информационная аналитика в управлении предприятием',
                                         'Право международной торговли, финансов и экономической интеграции',
 'Цифровые инновации в управлении предприятием (программа двух дипломов НИУ ВШЭ и Лондонского университета)',
                                                       'Суперкомпьютерное моделирование в науке и инженерии',
                                                                  'Политический анализ и публичная политика',
                                                                                       'Визуальная культура',
                                                          'Педагогичеcкая деятельность в условиях изменений']
Length: 340, dtype: str
Столбец 'education_level':
<StringArray>
['Магистратура', 'Бакалавриат', 'Специалитет']
Length: 3, dtype: str
Столбец 'course':
[2 4 3 5 6 1 nan]
Столбец 'group':
<StringArray>
['МФИИН231',  'БМБ2102',   'МЮП231',   'МЮБ232',  'МЭОС231',   'ММД231', 'МИНЯЗ231', 'МДРОБ232',   'СМК233', 'ММРЭК231',
 ...
  'МПР211С',  'МФЗ211С',  'МЯТ211С',  'БВВ183С',   'БЮР193',   'БЛГ204',  'БПД1910',   'БИИ192',   'МПТ221',   'МБК211']
Length: 3223, dtype: str
Столбец 'place_type':
<StringArray>
[                                             'Коммерческие',                                                 'Бюджетные',                'Коммерческие места для иностранных граждан',
                       'По межправительственным соглашениям',                         'Коммерческие за счет средств вуза',   'Места с оплатой стоимости обучения на договорной основе',
       'Места, обеспеченные государственным финансированием',                                                   'Целевые',                                 'Внеконкурсное поступление',
                   'Без вступительных испытаний (коммерция)',                               'Без вступительных испытаний',                                           'Сетевой студент',
                                                         nan, 'Коммерческие за счет средств вуза для иностранных граждан']
Length: 14, dtype: str
Столбец 'subject_name':
<StringArray>
[                                                                   'Дисциплина: Финансовые рынки: проблемы и решения',
                                                              'Дисциплина: Управление организационной жизнестойкостью',
                                                                                'Дисциплина: Отбор и назначение судей',
                                                                              'Дисциплина: Экономический анализ права',
             'Научно-исследовательский семинар: Семинар наставника "Экономика окружающей среды и устойчивое развитие"',
                                                                       'Дисциплина: Коммуникации в условиях изменений',
                                                  'Сервисный проект: Техническое сопровождение приемной кампании-2024',
                                                             'Дисциплина: Проектирование и разработка Edtech-продукта',
 'Научно-исследовательский семинар: Научно-исследовательский семинар "Разработка и внедрение корпоративных стратегий"',
                                                                                    'Дисциплина: Фитнес - образ жизни',
 ...
                                       'Дисциплина: Логистическая инфраструктура международных транспортных коридоров',
                                                           'Дисциплина: Контроль и мониторинг цифровых цепей поставок',
                                                        'Дисциплина: Цифровые сервисы в международной транспортировке',
                                    'Дисциплина: Инновационные технологии транспортировки в глобальных цепях поставок',
                          'Дисциплина: Инновационные технологии управления устойчивостью и надежностью цепей поставок',
                                                                          'Дисциплина: Цифровые технологии в обучении',
                                                                     'Дисциплина: Возрастная психология и образование',
                                                           'Дисциплина: Универсальные компетенции и новая грамотность',
                                             'Практика студентов: Технологическая (проектно-технологическая) практика',
                                                                                   'Дисциплина: Язык. Текст. Культура']
Length: 27052, dtype: str
Столбец 'exam_type':
<StringArray>
['Первая сдача', 'Пересдача', 'Полный перезачет', 'Пересдача с комиссией', 'Пересдача по уважительной причине', 'Частичный перезачет', nan]
Length: 7, dtype: str
Столбец 'subject_unit':
<StringArray>
[   'М_ФРПИР_П_676572_1',      'М_УОЖ_Г_909498_2',     'М_ОИНС_Г_800881_1',      'М_ЭАП_П_787475_1', 'М_СНЭОСИУР_Г_735356_1',     'М_КВУИ_Г_709005_1',                     nan,
     'М_ПИРE_Г_841746_1',  'М_НСРИВКС_Г_774883_3',     'М_Ф-ОЖ_П_907056_1',
 ...
     'М_ОРГ_Г_789352_51',       'М_ИР_П_790309_2',       'М_МА_П_789860_1',     'М_ТВИС_П_789936_2',       'М_П_Г_706287_12',       'Н_УУ_П_638559_1',      'Н_ЯТК_Г_748832_1',
 'Н_НСПИВЭИФ_П_640545_1',    'Н_НФИЮЛ_П_646663_1',    'М_ОРГ_Г_756303_230']
Length: 45460, dtype: str
Столбец 'grade_10':
[6 7 8 5 9 10 4 2 nan 0 3 1]
Столбец 'absence_status':
<StringArray>
[nan, 'invalid', 'valid', 'medical']
Length: 4, dtype: str
Столбец 'module':
[1 2 3 4 nan]
Столбец 'academic_year':
[2024 2023 2022 nan]
Столбец 'student_status':
<StringArray>
['graduated', 'study', 'expelled', 'leave']
Length: 4, dtype: str

In [31]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1767986 entries, 0 to 1767985
Data columns (total 16 columns):
 #   Column           Dtype
---  ------           -----
 0   student_id_hash  str
 1   campus           str
 2   faculty          str
 3   program          str
 4   education_level  str
 5   course           object
 6   group            str
 7   place_type       str
 8   subject_name     str
 9   exam_type        str
 10  subject_unit     str
 11  grade_10         object
 12  absence_status   str
 13  module           object
 14  academic_year    object
 15  student_status   str
dtypes: object(4), str(12)
memory usage: 215.8+ MB
None

In [ ]:
#table_df.to_csv('update_grades.csv', index=False, encoding='utf-8')